### ISSUE TITLE
can not find command "snip"

### ISSUE THREAD

**Issue by przemyslawjanpietrzak** [puyt/cerebro-snippets#2]
cerebro-snippets was install however cerebro can't find a snip/snipc/snipd commands.

Command `plugins snippets` display plugins (v1.1.0) however click on `settings` doesn't change anything.

Cerebro is in version `0.3.1`

**Comment by puyt** [comment]
Hmm that's weird.. I've used the latest version without any problems but since cerebro wouldn't run on ubuntu anymore i stopped using it in 2018 (this is also the time the project seems to be dead, no feedback from the maintainer since May 2018).

Since I can't run cerebro i can't check into this issue and i'm probably gonna archive this plugin since the main project is dead, feel free to fork it though.

Maybe you can try and cerebro `0.3.3` or downgrade this plugin to `1.0.3`

Sorry i can't help you any further.

**Comment by przemyslawjanpietrzak** [comment]
Downgrade to `1.0.3` works 🎉 . If you're planning to archive this I can take care of plugin. I know that cerebro is kind of dead however I  didn't find any (open source) alternative, so I'm stuck with him.

**Comment by puyt** [comment]
If i remember correctly it probably has something to do with the plugin settings being bugged in `0.3.1` of cerebro and i've added some extra settings to disable the keyword `snip` (#1).

You're right, it's a shame the project has died and there isn't any good alternative available for cross-platform..

>If you're planning to archive this I can take care of plugin

I'll add you as collaborator :+1:
